### ISSUE TITLE
ctrld open sourced ctrld/ctrld.me

### ISSUE THREAD

**Issue by Juev** [ctrld/ctrld.me#1]
Привет!

У меня в общей ленте выдается сообщение из сабжа. Причем выделяет его из общей массы.
Каким образом ты это реализовал??

Что для этого нужно сделать?

**Comment by ctrld** [comment]
Привет, Денис.
Отключил когда-то нотификации, только сейчас правил код и увидел тикет.
Хм... Ничего не делал, кроме того, что репозиторий был приватным, а я его перевёл в публичные

**Comment by Juev** [comment]
Понятно, спасибо!
Примерно об этом и подумал уже после того, как сформулировал тикет.
